"""
Django Settings for HR System Core Project

This file contains all configuration settings for the HR management system.
It includes database configuration (MongoDB via Djongo), authentication settings,
REST framework configuration, and application-specific settings.

Generated by 'django-admin startproject' using Django 6.0.2.
For more information: https://docs.djangoproject.com/en/6.0/topics/settings/
"""

# ============================================================================
# IMPORTS
# ============================================================================
from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# ============================================================================
# ENVIRONMENT SETUP
# ============================================================================
# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# SECURITY SETTINGS
# ============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
# In production, always set this via environment variable
SECRET_KEY = os.getenv(
    'SECRET_KEY', 
    'django-insecure--16gy=a*-##vz9n9b$u8w4$10b7xu$z9a54q@ptr7xv#0&=)9+'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Hosts allowed to access this application
# In production, restrict this to specific domains using ALLOWED_HOSTS env var
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# ============================================================================
# APPLICATION DEFINITION
# ============================================================================
INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps for REST API and authentication
    'rest_framework',              # Django REST Framework for API
    'corsheaders',                 # Cross-Origin Resource Sharing
    'rest_framework_simplejwt',    # JWT authentication

    # Custom HR system apps
    'authentication',   # User authentication and management
    'employees',        # Employee data management
    'tasks',           # Task assignment and tracking
    'attendance',      # Attendance and leave management
    'projects',        # Project management
    'chat',            # Internal messaging system
    'notifications',   # Notification system
]

# ============================================================================
# MIDDLEWARE CONFIGURATION
# ============================================================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration
ROOT_URLCONF = 'core.urls'

# ============================================================================
# TEMPLATE CONFIGURATION
# ============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application
WSGI_APPLICATION = 'core.wsgi.application'

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
# Using MongoDB via Djongo ORM adapter
# Connection details are loaded from environment variables
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': os.getenv('DB_NAME', 'hr_system_db'),
        'ENFORCE_SCHEMA': False,  # Allow flexible schema for MongoDB
        'CLIENT': {
            'host': os.getenv('DB_HOST', 'mongodb://localhost:27017/'),
            'serverSelectionTimeoutMS': 5000,
            'tlsAllowInvalidCertificates': True,  # For development only
            'tls': True,
        }
    }
}

# ============================================================================
# PASSWORD VALIDATION
# ============================================================================
# Validators to ensure strong password requirements
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================================
# INTERNATIONALIZATION
# ============================================================================
LANGUAGE_CODE = 'en-us'

# Timezone set to Nepal (Asia/Kathmandu)
TIME_ZONE = 'Asia/Kathmandu'

# Enable internationalization
USE_I18N = True

# Use timezone-aware datetimes
USE_TZ = True

# ============================================================================
# STATIC & MEDIA FILES
# ============================================================================
# URL prefix for static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Required for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# URL prefix for user-uploaded media files
MEDIA_URL = '/media/'

# Directory where uploaded media files are stored
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================
# Configuration for Django REST Framework
REST_FRAMEWORK = {
    # Use custom MongoDB-compatible JWT authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'authentication.auth.MongoJWTAuthentication',
    ),
    # Require authentication by default for all endpoints
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ============================================================================
# JWT AUTHENTICATION CONFIGURATION
# ============================================================================
# Settings for JSON Web Token authentication
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),      # Access token valid for 1 day
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token valid for 7 days
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': '_id',  # MongoDB uses _id instead of id
}

# ============================================================================
# CORS CONFIGURATION
# ============================================================================
# Allow all origins for development
# TODO: In production, set specific origins
CORS_ALLOW_ALL_ORIGINS = True # Fallback if specific origins fail
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173').split(',')

# ============================================================================
# CUSTOM USER MODEL
# ============================================================================
# Use custom User model from authentication app
AUTH_USER_MODEL = 'authentication.User'

# ============================================================================
# MISCELLANEOUS
# ============================================================================
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'