# Generated by Django 3.2.25 on 2026-02-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='_id',
        ),
    ]
