# Generated by Django 3.2.25 on 2026-02-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_id_user__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
