# Generated by Django 3.2.25 on 2026-02-06 11:50

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='507f1f77bcf86cd799439012', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
