# Generated by Django 3.2.25 on 2026-02-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_timelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='timelog',
            old_name='user',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='timelog',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
