# Generated by Django 3.2.25 on 2026-02-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='id',
            new_name='_id',
        ),
    ]
